In [20]:
import warnings
warnings.filterwarnings("ignore")

In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocabulary size
voc_size=10000

In [25]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [26]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9543, 864, 9165, 8243],
 [9543, 864, 9165, 4614],
 [9543, 6825, 9165, 647],
 [4473, 4998, 4830, 7490, 1639],
 [4473, 4998, 4830, 7490, 8739],
 [4852, 9543, 4758, 9165, 9090],
 [6210, 4197, 7560, 7490]]

In [29]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np

In [31]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9543  864 9165 8243]
 [   0    0    0    0 9543  864 9165 4614]
 [   0    0    0    0 9543 6825 9165  647]
 [   0    0    0 4473 4998 4830 7490 1639]
 [   0    0    0 4473 4998 4830 7490 8739]
 [   0    0    0 4852 9543 4758 9165 9090]
 [   0    0    0    0 6210 4197 7560 7490]]


In [32]:
## feature representation
dim=10

In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [34]:
model.build(input_shape=(None, sent_length))

In [35]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[[-3.03635132e-02, -6.37533516e-03,  4.73169200e-02,
          2.73474567e-02,  4.80280556e-02,  4.66083921e-02,
          1.74984448e-02, -3.97849306e-02,  1.79400109e-02,
         -1.89180262e-02],
        [-3.03635132e-02, -6.37533516e-03,  4.73169200e-02,
          2.73474567e-02,  4.80280556e-02,  4.66083921e-02,
          1.74984448e-02, -3.97849306e-02,  1.79400109e-02,
         -1.89180262e-02],
        [-3.03635132e-02, -6.37533516e-03,  4.73169200e-02,
          2.73474567e-02,  4.80280556e-02,  4.66083921e-02,
          1.74984448e-02, -3.97849306e-02,  1.79400109e-02,
         -1.89180262e-02],
        [-3.03635132e-02, -6.37533516e-03,  4.73169200e-02,
          2.73474567e-02,  4.80280556e-02,  4.66083921e-02,
          1.74984448e-02, -3.97849306e-02,  1.79400109e-02,
         -1.89180262e-02],
        [-4.00601514e-02, -4.19527180e-02,  3.86908986e-02,
          4.96346876e-03,  1.45145543e-02,  1.66602060e-03,
          2.46229656e-02, -4.19236422e-02,  3.446305

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 9543,  864, 9165, 8243], dtype=int32)

In [39]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[[-0.03036351, -0.00637534,  0.04731692,  0.02734746,
          0.04802806,  0.04660839,  0.01749844, -0.03978493,
          0.01794001, -0.01891803],
        [-0.03036351, -0.00637534,  0.04731692,  0.02734746,
          0.04802806,  0.04660839,  0.01749844, -0.03978493,
          0.01794001, -0.01891803],
        [-0.03036351, -0.00637534,  0.04731692,  0.02734746,
          0.04802806,  0.04660839,  0.01749844, -0.03978493,
          0.01794001, -0.01891803],
        [-0.03036351, -0.00637534,  0.04731692,  0.02734746,
          0.04802806,  0.04660839,  0.01749844, -0.03978493,
          0.01794001, -0.01891803],
        [-0.04006015, -0.04195272,  0.0386909 ,  0.00496347,
          0.01451455,  0.00166602,  0.02462297, -0.04192364,
          0.03446306,  0.01848913],
        [-0.00955429,  0.00348286, -0.01832554,  0.04080294,
          0.0174858 , -0.02511768, -0.01769563,  0.01882808,
          0.04408077,  0.00166886],
        [-0.04540152,  0.00843518,  0.03677842,  0.0